sudo: required
services:
    - docker

before_install:
    - docker build -t geetanshjindal/dummy -f ./client/Dockerfile.dev ./client/
script:
    - docker run geetanshjindal/dummy npm test -- --watchAll=flase
#
after_success:
    - docker build -t geetanshjindal/multi-client ./client
    - docker build -t geetanshjindal/multi-nginx ./nginx
    - docker build -t geetanshjindal/multi-server ./server
    - docker build -t geetanshjindal/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push geetanshjindal/multi-client
    - docker push geetanshjindal/multi-nginx
    - docker push geetanshjindal/multi-server
    - docker push geetanshjindal/multi-worker
     
deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: bbucket_name
    bucket_path: docker-multi
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: $AWS_SECRET_KEY
